project:
  type: website

website:
  title: "Dimitrios Mallios"
  navbar:
    logo: images/D-letter.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true
    # Custom color palette
    # You can further customize in styles.css



